print('Ваше имя:')
name = input()
print('Ваша фамилия:')
surname = input()
print('Ваше любимое животное:')
animal = input()
print('Ваш знак зодиака:')
sign = input()
print('Индивидуальный гороскоп для пользователя ', name, surname)
print('Кем вы были в прошлой жизни:', animal)
print('Ваш знак зодиака -', sign, ', поэтому вы - тонко чувствующая натура.')
