print('Введите название фильма:')
name = input()
print('Название кинотеатра:')
place = input()
print('Время сеанса:')
time = input()
print('Билет на', name, 'в кинотеатре', place, 'на', time, 'забронирован.')